//
//  ItemName.swift
//  smartList
//
//  Created by Steven Dito on 10/8/19.
//  Copyright © 2019 Steven Dito. All rights reserved.
//

import Foundation


#warning("not using yet")

enum GenericItem {
    
    case almond
    case almondButter
    case anchovy
    case apple
    case appleButter
    case appleSauce
    case apricot
    case asiagoCheese
    case asparagus
    case avocado
    case avocadoOil
    case babySpinach
    case bacon
    case bagel
    case bakedBeans
    case bakingPowder
    case bakingSoda
    case balsamicVinegar
    case banana
    case barley
    case basil
    case bayLeaf
    case bbqSauce
    case beef
    case beer
    case bellPepper
    case blackBeans
    case blackberry
    case blackOlive
    case blackPepper
    case bleuCheese
    case blueberries
    case bread
    case breadCrumbs
    case breakfastSausage
    case broccoli
    case broth
    case brownSugar
    case bun
    case burrito
    case butter
    case cabbage
    case cake
    case candy
    case cannelliniBeans
    case capers
    case carrot
    case catfish
    case cashew
    case cashewButter
    case cauliflower
    case cayenne
    case celery
    case cereal
    case champagne
    case cheddar
    case cherries
    case chicken
    case chili
    case chiliPowder
    case chips
    case chocolate
    case cilantro
    case cinnamon
    case coconutMilk
    case cod
    case coffee
    case cookie
    case corn
    case cottageCheese
    case crab
    case cracker
    case cranberry
    case cranberrySauce
    case creamOfChickenSoup
    case creamOfMushroomSoup
    case cucumber
    case cumin
    case curryPowder
    case dip
    case donut
    case duck
    case egg
    case eggNoodles
    case favaBeans
    case fennelSeeds
    case feta
    case fishSticks
    case flounder
    case flour
    case fries
    case garlic
    case garlicPowder
    case gin
    case ginger
    case goatCheese
    case granola
    case granolaBars
    case grapefruit
    case grape
    case greekYogurt
    case greenOlive
    case groundBeef
    case groundTurkey
    case guava
    case gym
    case haddock
    case halfAndHalf
    case halibut
    case ham
    case heavyCream
    case honey
    case hotDogs
    case hotSauce
    case hummus
    case iceCream
    case icing
    case italianSeasoning
    case jalapeno
    case jelly
    case juice
    case kale
    case ketchup
    case kidneyBeans
    case kiwi
    case lamb
    case lasagnaNoodles
    case lemon
    case lemonJuice
    case lettuce
    case limaBeans
    case lime
    case limeJuice
    case lobster
    case lunchmeat
    case macAndCheese
    case macaroni
    case mahiMahi
    case mango
    case margarine
    case marinara
    case melon
    case mayonnaise
    case milk
    case mozzarella
    case muffins
    case mushroom
    case mussels
    case mustard
    case nectarine
    case nutmeg
    case nuts
    case oatmeal
    case oats
    case onion
    case onionPowder
    case orange
    case oregano
    case oyster
    case pancakeMix
    case paprika
    case parmesan
    case parsley
    case pasta
    case pastry
    case peach
    case peanutButter
    case peanut
    case pear
    case pepper
    case pickle
    case pineapple
    case pintoBeans
    case pitaBread
    case pizza
    case plum
    case pomegranate
    case popcorn
    case pork
    case potRoast
    case potato
    case pretzel
    case provolone
    case quinoa
    case raspberry
    case redPepper
    case redWine
    case relish
    case rice
    case ricotta
    case roll
    case rosemary
    case rum
    case sage
    case saladDressing
    case salami
    case salmon
    case salsa
    case salt
    case sardine
    case sausage
    case seets
    case shrimp
    case snapper
    case soda
    case sole
    case soup
    case sourCream
    case soySauce
    case spinach
    case squash
    case steakSauce
    case strawberry
    case sugar
    case sunflowerButter
    case sweetPotato
    case swiss
    case swordfish
    case syrup
    case taterTots
    case tea
    case thyme
    case tilapia
    case tofu
    case tomato
    case tomatoPaste
    case tortilla
    case trout
    case tuna
    case turkey
    case turmeric
    case vanilla
    case vegetableOil
    case venison
    case vinegar
    case vodka
    case watermelon
    case whippedCream
    case whiskey
    case whiteWine
    case worcestershireSauce
    case yeast
    case yogurt
    case zucchini
    case other
    
    
}
